#Local properties for Rhino, please do not push this to version control if you don't know what you're doing!
#Sat Mar 29 12:50:38 CST 2025
concurrentContext=true
enableCompiler=false
generateMapping=false
optimizationLevel=0
